#!/bin/bash

# 备份当前的工作区的内容，从最近的一次提交中读取相关内容，让工作区保证和上次提交的内容一致。同时，将当前的工作区内容保存到暂存区中
git stash

# 拉取服务器上的代码到本地
git pull origin master

# 从暂存区读取最近一次保存的内容，恢复工作区的相关内容。由于可能存在多个Stash的内容，所以用栈来管理，pop会从最近的一个stash中读取内容并恢复
# git stash pop

# 显示暂存区中的所有备份，可以利用这个列表来决定从那个地方恢复。
# git stash list

# 清空暂存区。
# git stash clear
